language: cpp

matrix:
  include:
    - env:
        - OCPN_TARGET=xenial
      dist: xenial
      compiler: gcc
      script:
        - ./ci/travis-build-debian.sh

    - env:
        - OCPN_TARGET=trusty
      dist: trusty
      compiler: gcc
      script:
        - ./ci/travis-build-debian.sh
    - env:
        - OCPN_TARGET=osx
      os: osx
      osx_image: xcode10.2
      compiler: clang
      script:
        - ./ci/travis-build-osx.sh

    - env:
        - OCPN_TARGET=mingw
      services:
        - docker
      script:
        - ./ci/travis-build-mingw.sh


before_install:
  - >
    echo -n | openssl s_client -connect https://scan.coverity.com:443
    | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
    | sudo tee -a /etc/ssl/certs/ca


before_deploy:
  - >
    openssl aes-256-cbc -K $encrypted_831747f1d3db_key
    -iv $encrypted_831747f1d3db_iv  -in deploy_rsa.enc -out
    /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script:
  - if [ "$OCPN_TARGET" = "osx" ]; then scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null $TRAVIS_BUILD_DIR/build/*.dmg travis@ocpnci.kalian.cz:files/; fi
  on:
    branch: master
    tags: false

notifications:
  email: false

git:
  depth: 10

env:
  - secure: "KC+tdCF5pSgrguqDcU3ZIzt6qxhu35aSGQYOJnsXFrC7XN7ACVCsb6kxjboAAoStvKuVy89OZLy6vdFpoZ+sHv0RtguV0RO70IX/A6m5PYAvnAXRSdCWoR4EfaV3UhN6hjTLGD2Wy6Hdkave9tt4IWeM8tAi/wvtbfE012ra4jU="

addons:
  coverity_scan:
    project:
      name: "OpenCPN/OpenCPN"
      description: "OpenCPN"
    notification_email: pavel@kalian.cz
    build_command_prepend: "mkdir -p build; cd build; cmake ..; make clean"
    build_command: "make"
    branch_pattern: coverity_scan
