#ifndef ZCHXWXWIDGETQT_GLOBAL_H
#define ZCHXWXWIDGETQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZCHXWXWIDGETQT_LIBRARY)
#  define ZCHXWXWIDGETQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZCHXWXWIDGETQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZCHXWXWIDGETQT_GLOBAL_H
